abci.go
abci_test.go
errors/common.go
errors/common_test.go
errors/main.go
examples/errors/demo.go

Resolves #35 
Nicer stack traces for "%+v" and minimal debug info for "%v".
Also add a main file to demo.
`go run ./examples/errors/demo.go`

Better error printing

---

commands/server/init.go
examples/mycoind/commands/init_test.go

was already initialised effectively preventing
a user to do that.
Genesis time is now being updated to init time.
Force flag has been introduced to override re-init
protection.
A message is now being printed if the init was a success.
This still needs tests to be updated.

Introduced verbose feedback on Init in case the app

---

Gopkg.lock
Gopkg.toml
app/store.go
examples/mycoind/Makefile
examples/mycoind/app/app_test.go

Get chainID from initChain again
Update tests
Update pubKey indexing according to the new message format

Upgrade abci and tm versions

---

version.go
x/sigs/controller.go

We need this so we can sign with the ledger (it requires sha256 or sha512 or blake2b prehash before signing).
It shouldn't break anything except the js clients (which Simon updated already), as your go clients, should also use `BuildSignBytes` directly or indirectly before signing.
I would like to get this in a (breaking) bov release by the next testnet, so we can release the updated js libs with it.

Use sha512 prehash on signbytes in x/sigs

---

cmd/bcpd/app/app_test.go

Fix #15 
```
goos: darwin
goarch: amd64
pkg: github.com/iov-one/weave/cmd/bcpd/app
BenchmarkSendTx/100-10-8                    3000            516346 ns/op          120037 B/op       2428 allocs/op
BenchmarkSendTx/100-100-8                   5000            361264 ns/op           25591 B/op        477 allocs/op
BenchmarkSendTx/10000-10-8                  3000           1630130 ns/op          459321 B/op       9320 allocs/opBenchmarkSendTx/10000-100-8                 3000            467421 ns/op           69887 B/op       1273 allocs/op
BenchmarkSendTx/10000-1000-8                3000            392103 ns/op           40139 B/op        657 allocs/opBenchmarkSendTx/100000-10-8                 3000           8982331 ns/op         2159775 B/op      44498 allocs/op
BenchmarkSendTx/100000-100-8 …
```

Benchmark tests for SendTx

---

cmd/bcpd/app/app_test.go
cmd/bcpd/app/benchmark.txt

Workflow has been changed slightly to do the following for each benchmark iteration :
Run blocksize CheckTx
Update height
Begin block
Run blocksize DeliverTx
End block
Commit
```
BenchmarkSendTx/100-10-8                    3000            514055 ns/op          119221 B/op       2412 allocs/op
BenchmarkSendTx/100-100-8                   3000            338524 ns/op           23235 B/op        430 allocs/op
BenchmarkSendTx/10000-10-8                  3000           1460607 ns/op          456949 B/op       9273 allocs/op
BenchmarkSendTx/10000-100-8                 3000            462201 ns/op           68020 B/op       1238 allocs/op
BenchmarkSendTx/10000-1000-8               10000            405973 ns/op           44066 B/op        735 allocs/op
BenchmarkSendTx/100000-10-8 …
```

Sendtx benchmark with multisig

---

x/nft/base/handler.go
x/nft/blockchain/handler.go
x/nft/blockchain/model.go
x/nft/blockchain/msg.go
x/nft/bootstrap_node/handler.go
x/nft/bootstrap_node/model.go
x/nft/bootstrap_node/msg.go
x/nft/bucket.go
x/nft/errors.go
x/nft/errors_test.go
x/nft/model.go
x/nft/ticker/handler.go
x/nft/ticker/model.go
x/nft/ticker/msg.go
x/nft/username/handler.go
x/nft/username/model.go

Closes #183 
Adds some context to many of the common NFT errors.
ex. `ErrInvalidId` is not helpful when there are many sub-ids in the object that could trigger the issue (eg. chainId inside of a username nft). 
This now adds a bit of context to help debugging, especially client side, where there is not the luxury of unit tests and full stack traces.

Better NFT errors

---

x/nft/blockchain/handler_test.go
x/nft/blockchain/msg.go

Closes #181 
This allows the default, auto-generated tendermint chainIds to be valid, along with the chainIds used in the iov testnets.

Update blockchain id regexp

---

orm/bucket_test.go
orm/sequence.go
orm/sequence_test.go

Remove sequence duplicate prefix. Refactor and cleanup sequence code.
fix #168
This pull request came up much bigger than expected. :rabbit: :hole:

fix sequence key creation

---

x/escrow/handler.go
x/escrow/handler_test.go
x/escrow/model.go

Escrow `Bucket.Create` method documentation is updated to be acurate.
fix #170
I think `Bucket.Create` method should be removed and assignment of an escrow ID moved to `Deposit` method. Current implementation goes through many indirect steps to achieve something that would best done in one place.

fix bucket.Create method description

---

cmd/bnsd/client/client_test.go

The fix relaxes the condition that both test TX are in the same block.
Resolves #213

Fix flickering client test

---

cmd/bnsd/app/app_nft_test.go
x/nft/username/bucket.go
x/nft/username/handler_test.go

Use ; for chain address separator. * (asterisk) character is used to
represent human readable address as represented by bnsd. To not confuse
those two, pick different separator character.
resolve #196

x/nft/username: change chain address separator

---

x/nft/username/model.go
x/nft/username/model_test.go
x/nft/username/msg_test.go

Update the chain address validation to allow address to be minimum 2
characters long.
resolve #197

x/nft/username: allow minimal address length of 2 charactes

---

x/currency/errors.go
x/currency/model.go
x/namecoin/errors.go
x/namecoin/token.go
x/namecoin/wallet.go

Instead of defining custom invalid object error in each extension, use
the one defined in orm package.
resolve #240

refactor ErrInvalidObject error use

---

.travis.yml
cmd/bcpd/commands/start_test.go
cmd/bnsd/commands/start_test.go
examples/mycoind/commands/start_test.go
tmtest/tmtest.go

Refactor tests that are using tendermint server to skip the test if the
tendermint binary is not available.
resolve #220

refactor tests using tendermint server

---

Makefile
cmd/bcpd/app/codec.pb.go
cmd/bcpd/app/codec.proto
cmd/bnsd/app/app.go
cmd/bnsd/app/codec.pb.go
cmd/bnsd/app/codec.proto
x/nft/base/handler_test.go

Rebuild Tx messages in bcpd and bnsd. Apply new rules:
- range 1-50 is reserved for middlewares,
- range 51-inf is reserved for different message types,
- keep the same numbers for the same message types in both bcpd and bnsd
applications. For example, FeeInfo field is used by both and indexed at
first position. Skip unused fields (leave index unused).
Change enum declaration fields to be upper case (protobuf style guide).
resolve #239

Rebase application protobuf message indexes.

---

cmd/bcpd/commands/init_test.go
cmd/bnsd/commands/init_test.go
examples/mycoind/commands/init_test.go
x/nft/base/handler_test.go

Instead of using printing to stdout in tests use test logger. This
results is buffered logging and proper test resports.
fix #234

remove print from tests

---

cmd/lsc/lsc.go

All 3 formats are producting the same characters. Leave only one,
bacause they are all redundant.
Now the output is
```
weave $ go run cmd/lsc/lsc.go -limit 4
index  address
1      5AE2C58796B0AD48FFE7602EAC3353488C859A2B
2      1369E8BBB1384C964CBB3303696F5D3B179033A3
3      084430510E07F109B9ACF8BC62EF853A66BD8754
4      26E3C3612C28BA356DAF336370299DBBD5C8A77A
```

simplyfy cmd/lsc output

---

.travis.yml
Gopkg.lock
Gopkg.toml
cmd/bnsd/client/testdata/genesis.json
cmd/bnsd/client/testdata/wallets.json

resolve #206 
I had to update genesis files in order to pass the tests. I am not sure if new configuration makes sense, but I believe it is good enough for tests.

Tendermint upgrade

---

cmd/bnsd/app/init.go
cmd/bnsd/client/admin.go
cmd/bnsd/client/client.go
cmd/bnsd/client/tx.go
cmd/bnsd/scenarios/main_test.go
cmd/bnsd/scenarios/validator_test.go
cmd/bnsd/scenarios/wallet_test.go
x/validators/errors.go
x/validators/handler.go
x/validators/handler_test.go
x/validators/msg.go
x/validators/msg_test.go

* Add/ Remove validator
* Prevent empty validator updates crashing tendermint
* Fixes validator initializer not called

Validator scenario

---

gconf/doc.go
gconf/gconf.go
gconf/gconf_test.go
gconf/genesis.go
gconf/genesis_test.go

:warning: Please do not merge :warning: 
`gconf` package implements a set of operations on a global
configuration.
Configuration is stored in a database with an interface compatible with
`weave.KVStore`. Each value stored by configration is serialized using
JSON.
To load a configuration value, use one of the provided functions (`Int`,
`String`, etc.). In case of parsing issues they log an error and return
empty value for given type. This should not happen, unless database was
manually altered.
Next step is to add a support for runtime configuration update via
message sending.
resolve #202 
Please have a look and if this is the right direction, I will add tests and documentation.

Initial global configuration package implementation

---

cmd/bcpd/Makefile
cmd/bnsd/Makefile

This fixes the `install` target in the project makefile which delegates to the sub-project's makefiles.

Add install target to makefile

---

cmd/validators/main.go
cmd/validators/main_test.go

An example flow:
1. Create a transaction that configures a validator. This transaction
points to a multisig contract as an authentication method:
```
./validators multisig-new \
-power 7 \
-pubkey HsEV3BeuXBHWmpdLkdk8R43kGzZYeVhUspqrIYacJUw= \
-multisig 5AE2C58796B0AD48FFE7602EAC3353488C859A2B \
> request.tx
```
2. Send the `request.tx` around and ask people to sign it:
```
./validators multisig-sign \
-tm http://127.0.0.1:22345 \
-key d34c1970ae90acf3405f2d99dcaca16d0c7db379f4beafcfdf667b9d69ce350d27f5fb440509dfa79ec883a0510bc9a9614c3d44188881f0c5e402898b4bf3c9 \
< request.tx \
> request_signed_1.tx
```
3. Once enough signatures are collected, submit the transaction:
```
./validators multisig-submit \
-tm http://127.0.0.1:22345 \
< request.signed_1.tx
```
Multisig addresses: …

Extend validator CLI tool to support multisig.

---

cmd/bnsd/app/init.go
cmd/bnsd/main.go
cmd/bnsd/scenarios/nft_test.go
commands/server/getblock.go
commands/server/retry.go
orm/bucket.go
orm/bucket_test.go
store/btree.go
store/helpers.go
store/iavl/adapter.go

Note: this is currently forked from 0.11.1 tag to ensure complete compatibility with the test case that failed.
Adds two new subcommands to `bnsd` to support forensic work:
* `bnsd getblock <file> [-height=H]` will extract a json block from a blockstore.db
* `bnsd retry <abci.db> <block.json>` will rollback the database one step and run the last block again. Multiple runs can detect non-determinism

Replay tool

---

Makefile
prototool.yaml

Add `make lint` that will run protobuf linter on our codebase.
After finishing https://github.com/iov-one/weave/issues/262 all linter
errors should be gone and we can add `make lint` to our CI.
resolve #302

Add protobuf linter

---

x/coins.go
x/coins_test.go
x/distribution/handler.go

This functionality is not yet used anywhere.
part of #327
```
goos: linux
goarch: amd64
pkg: github.com/iov-one/weave/x
BenchmarkCoinsNormalize/nil_coins-4               500000000 3.69 ns/op
BenchmarkCoinsNormalize/zero_len_coins-4          500000000 3.70 ns/op
BenchmarkCoinsNormalize/two_unordered_coins-4     100000000 17.6 ns/op
BenchmarkCoinsNormalize/two_split_coins-4          10000000  187 ns/op
BenchmarkCoinsNormalize/four_normalized-4          50000000 32.6 ns/op
BenchmarkCoinsNormalize/six_not_normalized-4        1000000 1147 ns/op
BenchmarkCoinsNormalize/twelve_normalized-4        20000000 93.4 ns/op
BenchmarkCoinsNormalize/one_coin-4                300000000 5.66 ns/op
BenchmarkCoinsNormalize/two_normalized_coins-4    100000000 17.7 ns/op …
```

add coins normalize function

---

errors/errors.go
x/coin.go
x/coin_test.go
x/distribution/handler.go

implement Coin.Multiply overflow check
resolve #326

implement Coin.Multiply overflow check

---

errors/doc.go
errors/errors.go
errors/errors_test.go
errors/main.go
x/cash/decorator.go
x/cash/handler.go
x/coin.go
x/currency/handler.go
x/multisig/handlers.go
x/namecoin/handler.go
x/namecoin/init.go
x/nft/base/handler.go
x/validators/controller.go

Closes #311 
Adds the stacktrace on the first Wrap call, if it wasn't passed in (eg. from pkg/errors)
Future wraps just delegate `StackTrace()` to their parents.
`fmt.Printf("%s", err)` works just like always, returning `err.Error()`
Adds support for `"%+v"` working like pkg/errors, with full stack trace followed by the error message. Strips out boilerplate, such as errors.Wrap, errors.Error.New, runtime, etc to focus on the interesting lines.
Example:
```
github.com/iov-one/weave/errors.doWrap
/home/ethan/go/src/github.com/iov-one/weave/errors/errors_test.go:181
github.com/iov-one/weave/errors.TestStackTrace
/home/ethan/go/src/github.com/iov-one/weave/errors/errors_test.go:208
do the do: indirect
```
Also adds support for `"%v"` with minimal context, just the line number where error was …

Add stacktrace to new errors code

---

x/cash/dynamicfee.go
x/cash/dynamicfee_test.go

I wonder if this works as expected :thinking: 
~Tests will show once they will arrive :racing_car:~

Deduct min fee on error improvements and tests

---

x/cash/dynamicfee.go
x/cash/dynamicfee_test.go

Closes #349 
The `DynamicFeeDecorator` now checks the `RequiredFee` field in the result returned from the Handler it executes and if this is set and greater than the actual fee paid, it will rollback the transaction, deduct the anti-spam fee, and return an error.

Enforce required fee

---

x/cash/staticfee.go
x/cash/staticfee_test.go

Do not allow a minimal fee to not have a ticker.
resolve #369

Minimal fee requires a ticker

---

cmd/bnsd/app/init.go
cmd/bnsd/client/client.go
cmd/bnsd/scenarios/escrow_test.go
cmd/bnsd/scenarios/main_test.go
cmd/bnsd/scenarios/validator_test.go
cmd/bnsd/x/nft/username/bucket.go
conditions.go
conditions_test.go
x/cash/controller.go
x/cash/controller_test.go
x/distribution/handler_test.go
x/escrow/controller.go
x/escrow/init.go
x/escrow/init_test.go

This adds an escrow initializer and tests to create an escrow contract via genesis. The sender address must be set to the burn address to destroy the coins when not used by the escrow.
See: #310

Init escrow in genesis

---

Makefile

Use 3.7.0 instead of 3.4.0
But this doesn't change generated code at all... just to keep out any complaints of obsolete protoc.
@alpe Feel free to merge if desired, but you can skip as well

Upgrade protoc to 3.7.0

---

coin/coin_test.go
coin/coins_test.go
conditions_test.go
errors/doc.go
errors/errors.go
errors/errors_test.go
examples/tutorial/x/blog/handlers_test.go
weavetest/decorators_test.go
weavetest/handlers_test.go
x/cash/controller_test.go
x/cash/dynamicfee_test.go
x/currency/handler_test.go
x/distribution/handler.go
x/distribution/handler_test.go
x/distribution/model.go
x/distribution/model_test.go
x/msgfee/decorator_test.go
x/msgfee/model_test.go
x/multisig/handlers_test.go
x/paychan/handler_test.go
x/validators/controller_test.go
x/validators/handler_test.go

Change the implementation of `errors.Error.Is` and remove `errors.Is` function. Instead of using `ABCICode` to compare errors, use instance comparison and unwrapping. 
All cases are covered by the tests.
Existing code was updated as required.
This change does not implement `Is` method for the `Wrap` function result. Below is not possible.
> Our error instances are global and therefore comparable as instances. Using the above mechanism would also allow to "inherit" errors. Below can be true.

Refactor errors Is function

---

cmd/bnsd/scenarios/main_test.go

When running bnsd scenarios and using local server instance run it in
debug mode (the server). This will provide better insight into failures.
Part of https://github.com/iov-one/weave/issues/363

Run bnsd scenarios in debug mode

---

cmd/bnsd/app/app_performance_test.go
weavetest/abci.go

Some changes to how you were doing table-driven benchmarks.
Separate setup code for each different case (empty block, sendtx, distribute, etc...)
Tables to control parameters to cover larger spectrum of the performance (like multiple tx per block, with/without fees, num of multisig participants, etc)

Change benchmark tables

---

Makefile
cmd/bnsd/app/app_performance_test.go
weavetest/abci.go

One more as I was curious....
Allows ProcessAllTxs to do either:
* Check all, then Deliver all per block
* Only check all per block
* Only deliver all per block
* Check all with timer paused, then Deliver all with timer active (most realistic scenario for block time)
Interesting to see that in larger blocks (eg. 100), the time difference between Check and Deliver is minimal.

More detailed benchmarks

---

cmd/bnsd/app/app_performance_test.go
x/sigs/nonce.go

I think this is a great simplification of the nonce computation. Not caching allows to avoid errors and if using the database is an issue then increment the nonce value manually ([as done right now](https://github.com/iov-one/weave/compare/benchmarks_on_real_bnsd...benchmarks_on_real_bnsd_simplify_nonce?expand=1#diff-d1253d050ac787d66da49feebc759a91R174)).
The code was moved to `x/sigs` because it depends on the functionality provided by this extension. Nonce cannot be computed without importing `x/sigs`.
I do not like [`if !tc.strategy.Has(weavetest.ExecDeliver) && (k+1)%tc.txPerBlock == 0 {`](https://github.com/iov-one/weave/compare/benchmarks_on_real_bnsd...benchmarks_on_real_bnsd_simplify_nonce?expand=1#diff-d1253d050ac787d66da49feebc759a91R173) line as it requires too much knowledge …

simplify nonce counting in bnsd benchmark

---

cmd/bcpd/app/app_test.go
cmd/bnsd/app/app_test.go
cmd/bnsd/scenarios/main_test.go
weavetest/handlers.go
weavetest/results.pb.go
x/multisig/codec.pb.go
x/multisig/codec.proto
x/multisig/decorator.go
x/multisig/decorator_test.go
x/multisig/errors.go
x/multisig/handlers.go
x/multisig/handlers_test.go
x/multisig/init.go
x/multisig/init_test.go
x/multisig/model.go
x/multisig/msg.go
x/multisig/tx.go

`x/multisig` extension was updated and now each signature is having a
weight that defines what is the power of that signature.
- each signature power/weight must be greater than 0,
- activation threshold must be less or equal to the sum of all signature
powers,
- admin threshold can be greater than the sum of all signature powers.
This can be used to create a contract that can be only activated but
never changed,
- multisig contract must have at least one participant/signature
declared,
- maximum number of participants is 100 in order to prevent CPU burning,
resolve #285

 Extend multisig contract with weights

---

app/chain.go
app/chain_test.go

For ease of configuration allow to pass a nil value decorator to the
decorator chain builder. Nil decorator must be ignored.
resolve #414

allow to chain nil value decorator

---

.travis.yml
Makefile

Improvements to CI setup to shorten the execution time. Current build time is [18 min 51 sec](https://travis-ci.com/iov-one/weave/builds/105310606).
- Cache `GOPATH` between builds
Before using cache (empty cache, first run): Total time 19 min 4 sec 
First time after using cache (GOPATH restored):  Total time 16 min 2 sec :chart_with_upwards_trend: 
- Run coverage and binary/container builds only for the main Go version (1.11 right now).
- Build the container only if it will be published.
- Do not remove `vendor/`  directory
[Total time 12 min 51 sec](https://travis-ci.com/iov-one/weave/builds/105429273)   :tada:  - 6min improvement.
Addint one more Go version (1.12) will not make this process any longer.

Optimize CI tests

---

Makefile
coin/coin.go
coin/coin_test.go

Extend `coin.Coin` JSON deserialization with the support for a human
readable format. In addition to currently supported mapping into
structure fields accept a string in format:
"[-]<whole>[.<fract>] <ticker>"
This is an optional format supported only during deserialization.
Serialization to JSON is producing an object as before.
This is useful for https://github.com/iov-one/weave/issues/265

Support human readable JSON format for Coin.

---

weavetest/assert/assert.go
x/hashlock/context_test.go
x/hashlock/decorator_test.go

Before putting more energy into refactoring testing I want to make sure that I undestand the change correctly and that everyone is ok with this approach. This is a tiny pull request to verify this.
I have also updated the original story with a fresh description of what the task is https://github.com/iov-one/weave/issues/249
---
We have decided to cleanup weave tests and to follow a simple approach
of using standard library `testing` package with minimal set of helper
functions written by us.
- a `weavetest/assert` package was created, providing two test helper
functions
- `x/hashlock` was updated to show the direction of further changes
this is part of https://github.com/iov-one/weave/issues/249
---
What I think is awesome is that failing tests output looks very standard now. Below is an …

Initial test unification attempt

---

weavetest/assert/assert.go

Use `%+v` instead of `%#v` so that if we are printing an error value that
contains a stack trace information then the full stack trace is printed.

weavetest/assert: update log format

---

tx.go
tx_test.go
weavetest/tx.go
x/batch/decorator_test.go
x/batch/msg.go
x/cash/handler.go
x/cash/handler_test.go
x/currency/handler.go
x/distribution/handler.go
x/escrow/handler.go
x/hashlock/decorator.go
x/multisig/handlers.go
x/namecoin/handler.go
x/namecoin/handler_test.go
x/paychan/handler.go
x/validators/handler.go
x/validators/handler_test.go

Provide a `TxLoad` function that unpacks contained by a transaction
message and validates it. This is a replacement and simplification of
current flow where those two steps have to be done manually.
This is part of #437 
If this is the correct approach, I will refactor all handlers and decorators to use this function instead of manually extracting and validating the message.

provide TxLoad function for unpacking transaction message

---

x/escrow/codec.pb.go
x/escrow/codec.proto
x/escrow/time.go
x/escrow/time_test.go

When considering escrow expiration time make the comparison inclusive.
If current time is equal to the timeout value, escrow entity must be
considered expired.
resolve #446

x/escrow: make expiration time inclusive

---

store/btree_test.go
store/helpers_test.go

Refactor `store` package tests to not use testify and to use
map[string]struct{} for declaring test cases. Reduce amount of helper
functions.

store: refactor tests

---

orm/bucket.go
orm/bucket_test.go
orm/multiref.go

Update bucket tests to not use testify. Use map[string]struct{} to
declare test cases. Change some of the errors to use `errors` package
and test them using `errors.Error.Is` method.
This is not a complete orm package update, only `bucket_test.go` file.
part of #249

orm: update tests

---

errors/stacktrace_test.go

With go modules the project does not live within the Gopath anymore. This patch removes the assumption in `TestStackTrace` about the parent folder structure.

Remove parent project folders to work with modules

---

migration/register.go

Add a callback function `RefuseMigration` that should be used when there
is no migration path to given schema version. This function is intended
to be used for some message types and never for the model.
This is implementing one of the learning ideas from https://github.com/iov-one/weave/pull/591

migration: add a migration callback to refuse migration

---

errors/abci.go
errors/doc.go

- make `successABCICode` public variable
- update documentation
resolve #494

errors: update documentation

---

migration/handler.go
migration/handler_test.go

A new handler implementation is introduced.
`SchemaRoutingHandler` is a container that clubs toghether message
handlers for a single type message but different schema formats. Each
handler is registered together with the lowest schema version that it
supports. For example:
handler := SchemaRoutingHandler{
1: &MyHandlerVersionAlpha{},
7: &MyHandlerVersionBeta{},
}
In the above setup, messages with schema version 1 to 6 will be handled
by the alpha handler. Messages with schema version 7 and above are
passed to the beta handler.
It is not allowed to use an empty SchemaRoutingHandler instance. It is
not allowed to register a handler for schema version zero.
All messages processed by this handler must implement Migratable
interface.
Please note that it does not make sense to use …

migration: introduce a handler router based on message schema version

---

x/sigs/model.go
x/sigs/model_test.go

When incremeting a user sequence, ensure that the value does not exceed
the max value supported by the client (2^53 - 1).
resolve #511

x/sigs: when incrementing a sequence, check for overflow

---

CHANGELOG.md

I have manually edited and rewritten latest entries in the CHANGELOG
file. I have removed all points that were implementation specific (ie
tests) and are not important for the users.
I was trying to keep only information that is improtatnt for our users,
without going too much into implementation details.

CHANGELOG cleanup

---

abci.go
hex.go
store.go
store/iavl/adapter.go
version.go

weave: package improvements

---

CHANGELOG.md
migration/orm.go
migration/orm_test.go
orm/model_bucket.go
orm/model_bucket_test.go
weavetest/assert/assert.go
x/paychan/handler.go
x/paychan/handler_test.go
x/paychan/model.go

This is a proposal and a proof-of-concept implementation of a bucket
that operates directly on the model rather than Object instances.
This implementation relies on the Bucket to access the database. Final
implementation must not use Bucket but directly use KVStore instance.
Methods used (`One`, `Put`) are to be refined. I want to use something
very different than `Get` and `Save` of the existing bucket
implementation to avoid confusion and conflicts.
There are some more topics that are to be addressed before this
implementation is finished:
deserialization
looks good and is easy to use
resolve #536

orm: proposal of ModelBucket implementation

---

migration/handler.go
x/aswap/handler.go
x/cash/handler.go
x/currency/handler.go
x/distribution/handler.go
x/escrow/handler.go
x/gov/handler.go
x/multisig/handlers.go
x/namecoin/handler.go
x/paychan/handler.go

It is common to decorate with `SchemaMigratingHandler` all handlers before
registering. This requires quite some typing and passing everywhere the
same package argument. To simplify this process a new decorator is
introduced: `SchemaMigratingRegistry`.
The old way of registering a schema migration for a handler is:
var r weave.Registry
r.Handle("a", SchemaMigratingHandler("mypkg", myHandlerA)
r.Handle("b", SchemaMigratingHandler("mypkg", myHandlerB)
The above is equivalent to the below code enabled by this change:
r = SchemaMigratingRegistry("mypkg", r)
r.Handle("a", myHandlerA)
r.Handle("b", myHandlerB)

migration: provide schema migrating registry decorator

---

CHANGELOG.md

For 0.14.0 changes, confirm https://github.com/iov-one/weave/compare/v0.13.0...v0.14.0 and https://github.com/iov-one/iov-core/commit/5223b7f437350d270072b178cf10ac584f9ba15c

Add missing breaking change to 0.14.0

---

CHANGELOG.md
x/gov/handler.go
x/gov/handler_test.go

Follow up on #633 
Closes #586 
Make sure to update the tally even if executor fails.
We record success/error of option execution in the result.Log.
This is a minimal implementation of the changes discussed in https://github.com/iov-one/weave/pull/633#discussion_r285463618
I would like to merge this now to have a "correct" solution, rather than the error with the old format. We can gladly do a bigger change, one more devs have had time to discuss proper design. Discussion of what a "proper" solution is now it's own issue #649 .

Separate TallyMsg error from Executor error

---

cmd/cleanproto/.gitignore
cmd/cleanproto/Makefile
cmd/cleanproto/README.md
cmd/cleanproto/cleanproto.go
cmd/cleanproto/cleanproto_test.go
cmd/cleanproto/tests/codec.proto
cmd/cleanproto/tests/codec.proto.gold
cmd/cleanproto/tests/test.sh

A new command line tool for coleaning a protobuf file from a non
standard declarations, for example [gogoproto
options](https://godoc.org/github.com/gogo/protobuf/gogoproto).
Protobuf declaration is read from `stdin`. Result is written to `stdout`.
Example usage:
```
$ go run cmd/cleanproto/cleanproto.go < cmd/bnsd/app/codec.proto | wc -l
930
```
This is successor of https://github.com/iov-one/weave/pull/659 
fix #618

cmd/cleanproto: a new tool for cleaning protobuf

---

app/store.go
cmd/bcpd/app/app_test.go
cmd/bnsd/app/app_test.go
cmd/bnsd/app/testdata/fixtures/app.go
context.go
examples/mycoind/app/app_test.go
time.go
time_test.go
x/gov/handler.go
x/gov/handler_test.go

Add two new functions for comparing given time to "now" from the
context.
Use `weave.InThePast` and `weave.InTheFuture` instead of manually
comparing time with the result of `weave.BlockTime`.
`weave.BlockTime` notation was changed to return `error` instead of
`bool` as a second argument. This should signal that the second argument
must not be ignored.
`BlockTime` function use was almost completely replaced with two new
functions.
This is not implemented as described in #582 I think this solution is better as I often have time with comparing dates and using `After` and `Before` methods especially when combined with a time delta. I think having `InTheFuture` and `InThePast` makes it a bit easier to use.
#trivial
resolve #582

weave: add InThePast and InTheFuture functions

---

CHANGELOG.md
x/gov/codec.proto
x/gov/handler.go
x/gov/handler_test.go
x/gov/helpers_test.go

An electorate creation message must be signed by at least one of the
electorate members that this proposal is created for. In other words,
only those who are allowed to vote can approve a proposal creation.
I did not introduce `proposers_id` as I think this is exactly what `electorate_id` is.
resolve #670

x/gov: restrict who can create a proposal

---

abci.go
errors/abci.go
errors/abci_test.go
errors/multi.go
errors/multi_test.go

Features:
* Serialize mulitErr into json structure
* Move error Redact code into serialization step of `ABCIInfo(err error, debug bool) (uint32, string)`
Example:
```json
{
"data": [
{
"code": 4,
"log": "invalid message"
},
{
"code": 10,
"log": "invalid state"
}
]
}
```
See:
* #693 
* #529 
Reviewer notes:
- Errors on the json serialization are silently ignored and an empty json struct returned
#trivial

Rework abci error serialization with multiErr

---

CHANGELOG.md
cmd/bnsd/x/nft/username/model.go

Limit chain ids in bns usernames to 32, not 128 chars

---

Makefile
cmd/bcpd/Makefile
cmd/bnscli/Makefile
cmd/bnsd/Makefile
cmd/cleanproto/Makefile

`make tf` will still update go.mod (for local updates),
as will a manual `go build ...`, `go install ...`.
This ensures the official use of the Makefile and the CI run exactly what is in go.sum, and don't auto-update it.

Add -mod=readonly to all build commands and code run by CI

---

cmd/bnscli/cmd_cash.go
cmd/bnscli/cmd_cash_test.go
cmd/bnscli/cmd_distribution.go
cmd/bnscli/cmd_distribution_test.go
cmd/bnscli/cmd_escrow.go
cmd/bnscli/cmd_escrow_test.go
cmd/bnscli/cmd_gov.go
cmd/bnscli/cmd_gov_test.go
cmd/bnscli/common.go
cmd/bnscli/main.go

A new `cmd/bnscli` command `reset-revenue` was added. It allows to
create a transaction that reset (alters) an existing revenue entity.
```
weave $ cat /tmp/testdata.csv 
seq:foo/bar/1,3
seq:foo/bar/2,1
seq:foo/bar/3,20
weave $ bnscli reset-revenue -revenue aa -recipients /tmp/testdata.csv | bnscli view
{
"Sum": {
"ResetRevenueMsg": {
"revenue_id": "qg==",
"recipients": [
{
"address": "60AAA3D972FDA7AF6B7E6A9D5369BA40E5AD8071",
"weight": 3
},
{
"address": "ED6D7D79C5F147577AEF5F97E47C183377392D56",
"weight": 1
},
{
"address": "C684701657740CA240D9B28B3566E585A76905CD",
"weight": 20
}
]
}
}
}
```
#trivial

cmd/bnscli: add command to create a distribution reset transaction

---

cmd/bnscli/cmd_view.go

When `view`ing a proposal transaction the embeded message is base64
encoded binary representation of the content. Detect such case and print
the JSON representation of embeded message as well.
Example output:
$ bnscli release-escrow -amount "4 ABC" | bnscli as-proposal | bnscli view
{
"Sum": {
"CreateProposalMsg": {
"metadata": {
"schema": 1
},
"base": {
"title": "Transfer funds to distribution account",
"description": "Transfer funds to distribution account",
"election_rule_id": "AAAAAAAAAAA=",
"start_time": 1559737457
},
"raw_option": "qgMNCgIIARoHCAQaA0FCQw=="
}
}
}
The above transaction is a proposal for executing the following *escrow.ReleaseEscrowMsg message:
{
"metadata": {
"schema": 1
},
"amount": [
{
"whole": 4,
"ticker": "ABC"
}
]
}
#trivial

cmd/bnscli: print the embebed content of a proposal

---

cmd/bnscli/Makefile

Remove all dynamic linking when building `bnscli` binary.
#trivial
```sh
$ ldd ~/go/bin/bnscli 
not a dynamic executable
```
:tada:

cmd/bnscli: build as a static binary

---

CHANGELOG.md
cmd/bnsd/app/app_nft_test.go
cmd/bnsd/x/nft/username/bucket.go
cmd/bnsd/x/nft/username/handler_test.go

Previous implementation allowed only one alias per address. This allowed
for a reverse lookup (address by name) but also allowed to block an
alias registration. I could register my own name for your address and
prevent you to do the same.
This change removes reverse lookup as the index no longer exists. It
also allows for any number of usernames registered for the same address.
Please double check that my changes make logical sense.
While working on this change I have updated some of the tests. username registration is `bns` most important functionality and I think we should put more effort into bringing it to a great state. Right now, in my opinion, this is not something we should be confident to go to production with.
resolve #714

cmd/bnsd: allow many nft usernames for a single address

---

migration/orm.go
migration/register.go

#trivial 
I was working to add migration support to my custom model bucket in the tutorial, and realized it was impossible due to some private methods and objects, notably `reg`. I add two helper functions, so one can add migration support outside of the migrations package (in third party apps).

Expose migrations helpers

---

docs/proto/index.html
spec/gogo/x/gov/codec.proto
spec/proto/x/gov/codec.proto
x/gov/codec.pb.go
x/gov/codec.proto

hmm, now the ./spec folder gets out of date when I commit such changes from the Web UI.
#trivial

Fix initial value in comments of Proposal.status/.executor_result

---

README.md
docs/mycoind/installation.rst

Update "install doc" for Go module dependencies.
Resolves #780 
#trivial
README is still pointing to mycoind without mentioning how to install + start tendermint.

Fix install doc

---

CHANGELOG.md
app/helpers.go
errors/errors.go
orm/index.go
orm/query.go
store.go
store/helpers.go
store/helpers_test.go
store/iavl/adapter.go
store/iavl/iterator.go
store/iterator.go
store/test_suite.go

Closes #763 
Updated weave.Iterator interface to:
```golang
type Iterator interface {
// Next returns (nil, nil, ErrDone) when there are no more value left
Next() (key []byte, value []byte, err error)
Release()
}
```
Updated all code in store and orm that relied on it (including some larger refactoring of the btree iterator, which made it nicer to read).
No functionality changed, just API

Simplify store iterator

---

CHANGELOG.md
abci_test.go
errors/abci.go
errors/abci_test.go
errors/errors.go
errors/errors_test.go
errors/field.go
errors/field_test.go
errors/multi.go
errors/multi_test.go
errors/stacktrace_test.go
weavetest/assert/assert.go
weavetest/assert/assert_test.go
x/paychan/model.go
x/paychan/msg.go
x/paychan/msg_test.go

This is a big change to how multi-error is implemented internally with a
minimal change to the API.
In the previous implementation, the `multiErr` type was exposed throughout
the `errors` package. Many places were type casting to check if an error
is a `multiErr` instance and provided as special execution path for this
case. This result in an entangled implementation that is hard to extend.
Adding multi-error was breaking the previous pattern where the error
implementations (`Error`, `wrappedError`, stack trace) were not aware of
each other implementation and were using only common interfaces.
This change is a preparation to implement the `Field` function as discussed in
https://github.com/iov-one/weave/issues/730
This change removes all dependency and type check. A new interface …

refactor of multi error + field error implementation

---

x/cash/dynamicfee.go
x/cash/dynamicfee_test.go
x/utils/savepoint.go
x/utils/savepoint_test.go

Closes #778 
This ensures we properly handle errors when writing the cache to the backing store in DynamicFeeDecorator. I also fixed the same issue in Savepoint. The only other point in our stack that flushes Cache is app.CommitStore.Commit, which already properly handled any errors on write.
#trivial

Handle cache write error 

---

cmd/bnscli/clitests/keygen.test

I have missed 1 failing test in #806 which was caused by leading spaces with `wc`.
Fixes #782

Remove leading spaces with 'wc' on OSX

---

CHANGELOG.md
cmd/bnsd/app/testdata/fixtures/app.go
cmd/bnsd/client/testdata/genesis.json
cmd/bnsd/x/username/msg.go
tx.go
x/aswap/handler.go
x/aswap/msg.go
x/batch/msg.go
x/cash/handler.go
x/cash/msg.go
x/currency/msg.go
x/distribution/msg.go
x/gov/handler.go
x/gov/msg.go
x/sigs/msg.go
x/validators/handler.go
x/validators/msg.go

Unify all message path values to follow the same set of rules.
- all messages must follow the same naming pattern
`<package>/<message_name>`
- message path must be snake case
- `/` must be used only once as the package name separator
- `<package>` is the package name, for example `escrow` or `cash`
- `<message_name>` is the message name converted to snake case, for
example `CreateRevenueMsg` is `create_revenue`
resolve #802

unify all message path values

---

CHANGELOG.md
cmd/bnsd/app/app.go
cmd/bnsd/app/app_test.go
cmd/bnsd/app/gov_handler.go
weavetest/handlers.go
x/utils/action_tagger.go
x/utils/action_tagger_test.go
x/utils/key_tagger_test.go

Closes #596 
* Simple decorator to add standard action=msg.Path() tags.
* Added to the bnsd Stack as an example.
* Update tests

Action tagger

---

CHANGELOG.md
app/router.go
app/router_test.go
cmd/bnsd/app/app.go
cmd/bnsd/x/username/handlers.go
cmd/bnsd/x/username/msg.go
handler.go
migration/handler.go
migration/msg.go
x/aswap/handler.go
x/aswap/msg.go
x/cash/handler.go
x/cash/msg.go
x/currency/handler.go
x/currency/msg.go
x/distribution/handler.go
x/distribution/msg.go
x/escrow/handler.go
x/escrow/msg.go
x/escrow/msg_test.go
x/gov/handler.go
x/gov/msg.go
x/multisig/handlers.go
x/multisig/msg.go
x/paychan/handler.go
x/paychan/msg.go
x/sigs/handler.go
x/sigs/msg.go
x/validators/handler.go
x/validators/msg.go

Change the `app.Router` to require a message reference instead of the
message path as the first argument.
Remove all `const` declaration of message paths as they are no longer
needed and can be embeded directly in message `Path` method.
resolve #817

change app.Router interface

---

.travis.yml

Use cache for Go modules when running Travis CI.
Before: 9min and 10min 30sec.
After: 5min and 6min. 
:speedboat:

configure trafis to use cache

---

CHANGELOG.md

https://github.com/iov-one/weave/releases/tag/v0.18.0
- `bnsd/x/username` genesis initializer implemented and included in `bnsd`.
- Support gov proposal vote, deletion and tally in `bnscli`
- Support gov proposal text resolution, update electorate, update election rules in `bnscli`
- Added `x/utils.ActionTagger`: all `bnsd` transactions now have
`action=${msg.Path()}` tags. If there is a batch, there is one tag per
sub-message. If it is a governance tally, the TallyMsg as well as the
option (message executed on behalf of the governance stack) is tagged.
Breaking changes
- Unify all message paths to follow pattern `<package>/<message_name>`
- `app.Router` interface was changed. Handler registration requires a message
and not message path.
- Unify all message attribute names
- rename `src` …

0.18.0 release

---

store/iterator.go
store/iterator_test.go

```
WARNING: DATA RACE
Write at 0x00c0002348b0 by goroutine 15:
github.com/google/btree.(*BTree).ReplaceOrInsert()
/home/piotr/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:693 +0xfc
github.com/iov-one/weave/store.BTreeCacheWrap.Delete()
/home/piotr/weave/store/btree.go:128 +0x9c   
github.com/iov-one/weave/store.(*BTreeCacheWrap).Delete()
<autogenerated>:1 +0xe8                    
github.com/iov-one/weave/store.TestCacheIteratorReleaseRaceCondition()
/home/piotr/weave/store/iterator_test.go:21 +0x628
testing.tRunner()                                       
/home/piotr/.go_1.12.5/src/testing/testing.go:865 +0x163
```
#trivial

weave/store: iterator tests added

---

store/iterator.go
store/iterator_test.go

weave/store: iterator release race condition fixed
Ensure iterator `Release` method is synchronous. Otherwise a race condition on the database is possible because the reader goroutine can be still active after the `Release` call.
#trivial

weave/store: iterator tests added (#859)

---

Dangerfile
README.md

We use `#trivial` to allow merging a pull request without any
modyfications to the CHANGELOG file.
In addition, allow to use `!nochangelog` string to achieve the same
result.
`#trivial` is triggering GitHub's stupid autocompletion. It might also
be [confusing to people from outside of the project](https://github.com/iov-one/weave/pull/879#issuecomment-509959187) what it means.
Do not search for any of those strings in the pull request title as we
never put it there.

Allow to use !nochangelog to mark pull request.

---

cmd/bnsd/client/client.go
go.mod
go.sum

tmplibs were merged into tendermint and must no longer be used. This
change fix the double protobuf message registration.
!nochangelog

remove tmlibs import

---

x/sigs/decorator_test.go

The decorator test expected a fix order of calls. With the refactoring to map based test cases this order got lost and tests began to fail randomly.
This fix is also a refactoring of the test to separate the test cases which.
#trivial

Fix and polish flacky sigs/Decorator test

---

cmd/bnscli/README.md

Update `cmd/bnscli` documentation and provide description for some of
the test examples describing the use case.
As [described by Ethan](https://github.com/iov-one/weave/issues/853#issuecomment-509590729) this provides the executable examples that should be incorporated into our documentation.
@kmw101 can you have a look at both [the README](https://github.com/iov-one/weave/blob/faa1d33dc83e6fb9041f1d27b4d97c69b40770f8/cmd/bnscli/README.md#cookbook) and linked  there examples and let us know if this is good enough?
Resolve #853
!nochangelog

Update `cmd/bnscli` documentation

---

CHANGELOG.md
errors/field.go
x/aswap/model.go
x/aswap/msg.go
x/batch/msg.go
x/cash/model.go
x/cash/msg.go
x/cron/model.go
x/currency/model.go
x/currency/msg.go
x/distribution/model.go
x/distribution/msg.go
x/escrow/model.go
x/escrow/msg.go
x/gov/model.go
x/gov/msg.go
x/msgfee/model.go
x/multisig/model.go
x/multisig/msg.go
x/sigs/model.go
x/sigs/msg.go
x/validators/model.go
x/validators/msg.go

Update all extensions to use multi-error for validation errors. This
means that when validation a model or a message, we get all validation
errors together instead of only the first one.
resolve #890

use multierror for validation errors

---

x/cron/cron.go
x/cron/cron_test.go
x/cron/model.go
x/cron/model_test.go

When successfully executing a message as a cron task, store result log
information within the task result. This is useful for `TallyMsg` where
althugh the message processing was successful and returned no error, the
process failed and tally could not execute its functionality. The only
feedback `TallyMsg` is providing is the response log.
The final result might be confusing. It is possible that for a single cron task result:
- :heavy_check_mark:  a tally cron task executed successfully,
- :heavy_check_mark: tally message was handled without an error,
- :no_entry_sign:  proposal that the tally was created for could not successfully execute stored procedure (failed) 
resolve #905
!nochangelog

x/cron: store cron executed message log

---

store/iavl/iterator.go
store/iavl/iterator_test.go

When an active iterator is released, a race condition is created. Write
to a closed `read` channel is performed. Restructure how the iterator is
implemented to eliminate the race condition.
Tests are added to confirm that the change fix the issue.
!nochangelog

store/iavl: fix iterator race condition

---

CHANGELOG.md
cmd/bnsd/x/username/username.go
cmd/bnsd/x/username/username_test.go

Restrict name registration to only iov domain as the only available
domain. This restriction is needed because for MVP release we do not
provide any namespace implementation. You cannot register and maintain
namespaces. To avoid chaos and radom namespace usage, we allow only iov
for now.
resolve #907

bnsd/username: allow for only iov domain

---

CHANGELOG.md
cmd/bnscli/cmd_query.go

When a query result returns a proposal, in addition to printing a JSON
serialized proposal structure include deserialized raw options value.
This allows the user to inspect what message is being proposed and voted
on.
resolve #914

cmd/bnscli: improve how proposal is formatted when queried

---

CHANGELOG.md
cmd/bnscli/cmd_submit.go
cmd/bnscli/cmd_submit_test.go

When a transaction is submitted, for certain messages parse returned
response data and print it in a human readable format. For example, when
submitting a proposal, a decimal ID value of created proposal will be
printed.
resolve #913

cmd/bnscli: parse submit command output

---

.travis.yml

* Solves git hash length issue by switching to `bionic` distro
* Fails fast now with piped commands

Travis gitian build fix

---

CHANGELOG.md
cmd/bnscli/cmd_query.go
orm/versioning_bucket.go
orm/versioning_bucket_test.go
x/gov/bucket_test.go

Fixes #918 
You will notice that prefix queries should be done by id alone, because there is no way we can consistently deserialise if we ignore `Version` when it is zero.
This also needs bnscli changes, but first I'd like to validate the approach.

orm: deterministic versionedIDRef serialization

---

.travis.yml
orm/versioning_bucket_test.go

rollback travis VM to Ubuntu 16.04
Using Ubuntu 18.04 does not pass the bnscli tests. For some reason,
client is not able to connect to a tendermint server running on
localhost:4444.
!nochangelog

Rollback travis CI to Ubuntu 16.04

---

.travis.yml
contrib/gitian-descriptors/bns-linux.yml

> Instead of using the default 7 hexadecimal digits as the abbreviated object name, use <n> digits, or as many digits as needed to form a unique object name
https://git-scm.com/docs/git-describe#Documentation/git-describe.txt---abbrevltngt

Set git hash length explicitely for CI

---

CHANGELOG.md
cmd/bnscli/cmd_query.go

Query support in `bnscli` was extended. New supported endpoints are
- `/escrows`
- `/revenues`
- `/contracts`
fix #925

bnscli: support for more queries

---

cmd/bnsd/client/tx.go
cmd/bnsd/client/tx_test.go

When looking through client code I noticed this `ParseBcpTx`. This module was removed on _v0.17.0_. So I thought maybe rename this to `ParseBnsdTx` for convenience? Maybe remove this function, I can't see its use anywhere.
!nochangelog

cmd/bnsd/client: rename ParseBcpTx to ParseBnsdTx

---

cmd/bnsd/main.go

I noticed `testgen` help message is missing. Maybe add?
!nochangelog

cmd/bnsd: add testgen generation to help message

---

cmd/bnscli/cmd_submit.go

Any submission error is currently ignored and we see instead:
```
response: %!q(<nil>)cannot extract response: cannot format #0 result data : cannot parse sequence: sequence must be 8 bytes: ""
``` 
!nochangelog

Handle submission error in bnscli

---

cmd/bnscli/main_test.go
tmtest/tmtest.go

While I was working on `customcli` in weave-starter-kit, I noticed `main_test.go` depends on `RunBnsd` method which is not generic at all. I refactored it to be easily used by weave based projects.
!nochangelog

tmtest: refactor RunBnsd method to be generic

---

CHANGELOG.md
migration/model.go
migration/orm.go
migration/orm_test.go
orm/bucket.go
orm/bucket_test.go
orm/idgen_bucket_test.go
orm/interfaces.go
orm/model.go
orm/model_bucket.go
orm/object.go
orm/object_test.go
orm/versioning_bucket_test.go
x/aswap/model.go
x/cash/model.go
x/cron/model.go
x/currency/model.go
x/distribution/model.go
x/escrow/handler_test.go
x/escrow/model.go
x/gov/bucket.go
x/gov/model.go
x/msgfee/model.go
x/multisig/model.go
x/paychan/model.go
x/sigs/model.go
x/validators/model.go

Simplify `orm` package by reducing interfaces. Instead of relying on `orm.Cloneable`, `orm.CloneableData`, `orm.SimpleObj` and others, expect a model structure to implement only `orm.Model`.
resolve #986

orm: simplify interfaces a model must implement

---

cmd/bnscli/main_test.go
cmd/bnscli/testdata/config/genesis.json
tmtest/tmtest.go

`x/msgfee` was extended to provide a message to set a fee for a given
message path. Use zero value amount to delete a fee. Transaction for
setting a message fee must be signed by the fee administrator.
Fee administrator is set in the `x/msgfee` configuration, using gconf
and should be initialized with the genesis file.
The messsage fee setting message was added to `bnsd` and `bnscli`.

x/msgfee: add message to change the message fee value

---

COMPATIBILITY.md
README.md

I thought compatibility charts filled too much space in the main `README.md` file so moving it to a new file favor repo cosmetics. If you have the same idea press the `approve` button 😄

Move compatibilty charts to a new file

---

.travis.yml

Allow CI builds for release branches that follow our tag convention with a `x` wildcard in the end. For example `v0.21.x`.

Enable travisCI build for release branches

---

CHANGELOG.md
x/msgfee/antispam_fee_decorator.go
x/msgfee/antispam_fee_decorator_test.go

The handlers sets the antispam fee instead of returning an error and rejecting the Tx.
Fixes #1001

Let AntispamFeeDecorator handle empty product fee

---

CHANGELOG.md
x/msgfee/antispam_fee_decorator.go
x/msgfee/antispam_fee_decorator_test.go

The handlers sets the antispam fee instead of returning an error and rejecting the Tx.
Fixes #1001

Fix AntispamFeeDecorator to handle empty product fee

---

orm/versioning_bucket.go
store.go

Previous implementation was fetching all elements of a range under the hood while we only need a single one. No api changes involved.
!nochangelog

Optimize get latest version

---

crypto/ed25519_test.go

From Audit:
> Severity: Informational
Status: Open
Description
The function PrivKeyEd25519FromSeed that is critical for the generation of wallets is not
covered by any unit test and could, therefore, be prone to future errors being implemented
without being detected.
I fixed this _vulnurability_ in my free time. From now on Weave is bulletproof :joy:
!nochangelog

crypto: fix missing PrivKeyEd25519FromSeed audit vulnurability

---

cmd/bnsd/x/blueaccount/handler.go
cmd/bnsd/x/blueaccount/handler_test.go

Only a domain owner can transfer Blue Account accounts. If a Blue
Account account has an additional owner set, this additional owner is
not allowed to transfer the account. An account owner can delete an
account.
resolve #1037
!nochangelog

update blue account transfer permissions

---

orm/serial_bucket.go

I unnoticed the potential validation error when saving a serial model without preset **Primary Key**.
When a model is being saved to the store, validation is run before setting the primary key.
```go
if err := m.Validate(); err != nil {	
return errors.Wrap(err, "invalid serialmodel")	
}
```
For example this is the blog model from blog-tutorial:
```go
// Validate validates blog's fields
func (m *Blog) Validate() error {
var errs error
errs = errors.AppendField(errs, "Metadata", m.Metadata.Validate())
errs = errors.AppendField(errs, "PrimaryKey", orm.ValidateSequence(m.PrimaryKey))
errs = errors.AppendField(errs, "Owner", m.Owner.Validate())
```
`orm.ValidateSequence(m.PrimaryKey)` throws error because the primary key is not set.
!nochangelog

orm: Fix PrimaryKey validation error on serial model bucket save

---

CHANGELOG.md
cmd/bnsd/x/blueaccount/handler.go
cmd/bnsd/x/username/handlers.go
go.mod
x/auth.go
x/auth_test.go
x/cash/dynamicfee.go
x/cash/staticfee.go
x/escrow/handler.go
x/gov/handler.go
x/multisig/handlers.go
x/sigs/handler.go

`MainSigner` function returns always the first condition as defined in
the transaction. Using this function can introduce a security hole. One
must never assume the order of transaction signatures, because those are
not part of signed content. Order of signatures in transaction can be
altered at any time.

x: deprecate and rename `MainSigner`

---

CHANGELOG.md

- `x/sigs` allow to explicitly specify which user to bump the sequence for
instead of relying on the transaction signatures.
- `x/username` when registering a token, allow to explicitly specify the new
token owner instead of relying only on the transaction signatures.
Breaking changes
- deprecate and rename `x.MainSigner` to `x.AnySigner` to better describe
provided functionality.

release 0.23.0

---

CHANGELOG.md
migration/orm.go
orm/bucket.go
orm/bucket_test.go
orm/index.go
orm/index_test.go
orm/model_bucket.go
orm/model_bucket_test.go

`orm` package was updated and provides a new index implementation, that
is using a native database store in order to maintain and iterate
through an index. `orm.Bucket` and `orm.ModelBucket` were updated to
allow for the use of the new index implementation.
`orm.Index` is an interface now to allow multiple implementations. The
new interface is a subset of the old structure, simplified and updated
to support lazy loading:
- `Keys` method returns an iterator
- `GetLike` method was removed
`orm.Bucket` interface was simplified. `GetIndexedLike` was removed.
`orm.WithIndex` supports multiple indexer types.
`orm.NewIndex` function was removed.
resolve #1059

orm: implement database native index

---

CHANGELOG.md
cmd/bnsd/app/datamigration.go
cmd/bnsd/app/datamigration_test.go
datamigration/handler.go
datamigration/handler_test.go
datamigration/registry.go
datamigration/registry_test.go
orm/model_bucket.go
orm/model_bucket_test.go

A new `bnsd` data migration was registered to rewrite all `username`
tokens to `account` extension.

bsnd: data migration for rewriting username entities to account

---

CHANGELOG.md
x/msgfee/init.go
x/msgfee/init_test.go

When initializing `x/msgfee` extension from genesis, allow for no
configuration. Previously such setup would fail initialization. Now it
quietly ignores missing configuration.
fix #1082

x/msgfee: configuration is genesis is optional

---

CHANGELOG.md
x/sigs/handler.go
x/sigs/handler_test.go
x/sigs/msg.go
x/sigs/msg_test.go

`sigs.BumpSequenceMsg.User` is now required and cannot be empty. This is
a backward incompatible security fix.
resolve #1087

`x/sigs`: `BumpSequenceMsg.User` is now required

---

CHANGELOG.md
docs/proto/index.html
spec/gogo/x/escrow/codec.proto
spec/proto/x/escrow/codec.proto
x/escrow/codec.pb.go
x/escrow/codec.proto
x/escrow/handler.go
x/escrow/handler_test.go
x/escrow/msg.go
x/escrow/msg_test.go

`escrow.CreateMsg.Source` is no longer optional and is now required.
This is a backward incompatible security fix.
resolve #1086

x/escrow: `CreateMsg.Source` is now required

---

orm/index.go
orm/index_test.go
weavetest/store.go

When storing an index, do not use `nil` as value. `nil` is not accepted
by all backends.
Update tests to use hard drive backed storage instead of in memory
implementation to ensure the functionality works.
!nochangelog

fix native index tests

---

cmd/bnsd/app/datamigration.go
orm/model_bucket.go

`ModelBucketIterator.Next` returns an entity key, which should be a
`[]byte` and not `string`.
!nochangelog

orm: improve ModelBucketIterator.Next notation

---

docs/proto/index.html
spec/gogo/x/cash/codec.proto
spec/gogo/x/gov/codec.proto
spec/proto/x/cash/codec.proto
spec/proto/x/gov/codec.proto
x/cash/codec.pb.go
x/cash/codec.proto
x/gov/codec.pb.go
x/gov/codec.proto

For each affected by the `x.AnySigner` function message add a warning
explanation why a value should be always explicitly specified.
!nochangelog

update protobuf messages documentation

---

.travis.yml
CHANGELOG.md
x/txfee/decorator.go
x/txfee/decorator_test.go

When configuration entity was not created for the `x/txfee` extension,
middleware provided by `x/txfee` is a no-op. This behaviour allows for
backward compatibility with an existing blockchain and easy introduction
of the middleware.
@davepuchyr I hope this solves the issue that you have with running a new network.

x/txfee: update behaviour when configuration does not exist

---

x/gov/handler.go
x/gov/handler_test.go

When a proposal failed to execute, include that proposal ID for the ease
of tracking.
@davepuchyr notice that the ID is a binary data, not a numeric value. This is because this binary key might contain encoded number, but that does not have to be always true. Is this acceptable?
!nochangelog

include proposal ID in relivery log

---

cmd/bnsd/x/account/handler.go
cmd/bnsd/x/account/handler_test.go

A domain without a superuser cannot be deleted or transferred.
resolve #1137
!nochangelog

update account transfer and deletion rules

---

cmd/bnsd/app/datamigration.go

It is not tenable for the owner of the preregistration configuration to be technicalExecutors because they are required to submit a proposal for every pre-registered domain.  `bnscli preregistration-update-configuration` can set the owner to anyone and, therefore, can write pre-registered domains onto the chain via script.
!nochangelog

datamigration: drop initializePreregistrationConfiguration

---

CHANGELOG.md
cmd/bnsd/app/app.go
cmd/bnsd/app/cashctrl.go
cmd/bnsd/app/cashctrl_test.go
x/cash/controller.go

`bnsd` cash controller was updated and now it ensures that zero address
wallet (`iov1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvnwh0u`) never exist.
Sending any funds to that address removes them from the system as all
funds are instantly purged after transfering.
resolve #1140

bnsd: keep the zero address wallet empty

---

CHANGELOG.md
cmd/bnsd/app/app.go
cmd/bnsd/x/preregistration/decorator.go

A new preregistration decorator was added to `bnsd`. When `bnsd` is
configured correctly the newly added decorator allows for submitting
`preregistration.RegisterMsg` without any fee.
resolve #1143

bnsd: allow for a zero fee for preregistation record msg

---

CHANGELOG.md
cmd/bnsd/x/account/handler.go
cmd/bnsd/x/account/handler_test.go

Resolves https://github.com/iov-one/weave/issues/1191
Domain expiration time becomes domain.ValidUntil + configuration.DomainRenew
In case this time appears to be in the past compared to current block time, then the new domain expiration becomes current block time + configuration.DomainRenew

Renew domain expiration time update

---

CHANGELOG.md
cmd/bnsd/x/account/handler.go
cmd/bnsd/x/account/handler_test.go

Resolves https://github.com/iov-one/weave/issues/1207

feature/account: non-superuser domains cannot be flushed

---

cmd/dumpstate/cash.gold.json
cmd/dumpstate/dumpstate.go

Resolves https://github.com/iov-one/weave/issues/1216
!nochangelog
I used `weave.NewAddress` to convert database key (which exactly equals to byte representation of wallets address), I got carried and did not check the content of the NewAddress but internally this function hashes the key again. Nice catch @davepuchyr

Fix dumpstate cash address bug
