.circleci/config.yml, .codecov.yml, .gitignore, Makefile, README.md, coverage/upload.sh, errors/main.go
Upload from circle ci on every commit
Display on the prs
Don't enforce the codecov to merge... yet
=> Add codecov support

Makefile, util_test.go, x/auth_test.go, x/helpers.go, x/helpers_test.go, x/persistent_test.go, x/sigs/controller_test.go
Go through the worse offenders from codecov to make sure it all makes sense.
=> Improve test coverage

Makefile
Resolves issue #44 
good call @jpincas
=> Remove non longer needed glide mirror command

x/cash/controller.go, x/cash/controller_test.go
Partially addresses #20 
Cover some more cases
=> Improve x/cash tests

docs/mycoind/installation.rst, examples/mycoind/run.sh
- not suggesting this is merged yet
- and this is not targeted at any one specific feature/issue
- just created to register the fact that I have created a new unspecific branch to collect up some initial, very minor contributions
=> Wip: Jons first pr

Gopkg.lock, Gopkg.toml, abci.go, examples/mycoind/Makefile
=> tm version bump

conditions.go, crypto/ed25519.go, crypto/ed25519_test.go, crypto/helpers.go, docs/design/permissions.rst, errors/common.go, errors/common_test.go, tx.go, util_test.go, x/auth.go, x/auth_test.go, x/cash/decorator_test.go, x/cash/handler_test.go, x/helpers.go, x/sigs/context.go, x/sigs/controller.go, x/sigs/controller_test.go, x/sigs/decorator.go, x/sigs/decorator_test.go
* Rename Permission to Condition
* Clean up documentation
* Minor fixes
=> Clean up permission implementation

.travis.yml, Makefile, cmd/bcpd/Makefile, examples/mycoind/Makefile, examples/mycoind/run.sh
* Replace Gopath tendermint update with docker
* Build bcpd docker artifact via travis
Note to reviewer: bpcd tests are executed vie main Makefile and bcpd/Makefile. I did not optimize this
=> CI build updates

abci.go, abci_test.go, app/base.go, cmd/bcpd/app/app.go, cmd/bcpd/app/app_test.go, cmd/bcpd/app/init.go, commands/server/start.go, examples/mycoind/app/app.go, examples/mycoind/app/app_test.go, examples/mycoind/app/init.go
=> Tx result call stack dislay controlled by flag

architecture/NFT.md
This is a beginning designing what we want with NFTs.
Please expand on this and complete it to a point that it can inform development.
Resolves #103
=> WIP: NFT architecture document

cmd/bcpd/app/app.go, x/nft/approvals.go, x/nft/errors.go, x/nft/model.go, x/nft/model_test.go, x/nft/username/handler.go, x/nft/username/handler_test.go, x/nft/username/model.go, x/nft/username/model_test.go, x/nft/username/msg.go, x/nft/username/msg_test.go
Request handler implementation to issue new username tokens.
- excluding approvals
=> Username handler issue

cmd/bcpd/app/init.go
=> Validate ticker passed with init and return nice error if invalid

docs/mycoind/installation.rst
Update tendermint install instructions
=> WIP: Doc update

cmd/bcpd/app/app_test.go
=> multisig contract cleanup

cmd/bcpd/app/app.go, x/nft/errors.go, x/nft/username/bucket.go, x/nft/username/codec.pb.go, x/nft/username/codec.proto, x/nft/username/handler.go, x/nft/username/handler_test.go, x/nft/username/model.go, x/nft/username/model_test.go, x/nft/username/msg.go, x/nft/username/msg_test.go
* Apply model changes with spec update https://github.com/iov-one/weave/issues/104
* Add/ Remove chain address
=> Model updates; add/remove chain address

x/namecoin/errors.go, x/namecoin/errors_test.go, x/namecoin/handler_test.go
=> Fix ErrNoSuchWallet format and adding a test for it 

cmd/bnsd/app/app_nft_test.go, orm/bucket.go, orm/index.go, orm/index_test.go, x/nft/username/bucket.go, x/nft/username/handler.go, x/nft/username/handler_test.go, x/nft/username/model.go, x/nft/username/model_test.go, x/nft/username/msg_test.go
* Add multi key index
* Chain address must not be null
=> Username idx

x/nft/username/handler.go, x/nft/username/handler_test.go
* Add tag to abci response for issue username transactions
=> Tag issue username tx

docs/mycoind/installation.rst
Tendermint documentation was moved to GitHub pages.
=> update broken tendermint documentation link

cmd/bnsd/app/init.go, x/nft/blockchain/init.go, x/nft/blockchain/init_test.go
Provide initializer for nft extension, that will consume blockchain
token declaration from a genesis declaration and store it in the
database.
close #184
=> allow to initialize nft blockchain token with genesis

cmd/bnsd/app/app_nft_test.go, cmd/bnsd/app/examples.go, cmd/bnsd/scenarios/nft_test.go, x/nft/username/bucket.go, x/nft/username/codec.pb.go, x/nft/username/codec.proto, x/nft/username/handler_test.go, x/nft/username/model.go, x/nft/username/model_test.go, x/nft/username/msg_test.go
=> convert chainAddress to string

LICENSE, README_BOV.md, docs/conf.py
=> Update copyright year

cmd/bcpd/app/init.go, cmd/bnsd/app/init.go
As requested in https://github.com/iov-one/weave/pull/254#pullrequestreview-189375617
=> install multisig initializer in bcpd and bnsd

cmd/bcpd/app/app.go, cmd/bcpd/app/app_test.go, cmd/bnsd/app/msg.go, cmd/bnsd/scenarios/nft_test.go
@ethanfrey you were right about testing with last failure.
fixes https://github.com/iov-one/weave/issues/237
We really need to revisit these app tests eventually, even adding a small change is a pain.
=> fix batch bcp integration and tests

app/commit.go, app/store.go, x/nft/ticker/handler_test.go
Part of https://github.com/iov-one/weave/issues/224
Benchmark for `ticker` submodule only.
```
goos: linux
goarch: amd64
pkg: github.com/iov-one/weave/x/nft/ticker
BenchmarkIssueToken/with_check_no_deliver_block_size_10-4                  10000            117886 ns/op
BenchmarkIssueToken/no_check_with_deliver_block_size_10-4                  10000            748761 ns/op
BenchmarkIssueToken/with_check_with_deliver_block_size_1-4                  5000           1522167 ns/op
BenchmarkIssueToken/with_check_with_deliver_block_size_10-4                10000            713678 ns/op
BenchmarkIssueToken/with_check_with_deliver_block_size_100-4               10000            605895 ns/op
```
=> Nft benchmark issue 224 2

x/nft/blockchain/codec.proto, x/nft/blockchain/doc.go, x/nft/bootstrap_node/doc.go, x/nft/codec.proto, x/nft/doc.go, x/nft/ticker/doc.go, x/nft/username/codec.proto, x/nft/username/doc.go
Add doc.go and comments for protobuf declarations.
Please check if what I wrote makes sense.
=> nft documentation

cmd/bnsd/scenarios/validator_test.go, x/validators/doc.go
Acceptance test scenario to query signatures for validator set updates
=> Query validator update signers

cmd/bnsd/app/init.go, orm/index.go
=> Imports only

Gopkg.lock, Gopkg.toml
Upgrade tendermint version to v0.29.1
=> Upgrade tendermint version to v0.29.1

cmd/bnsd/app/init.go, cmd/validators/main.go, crypto/helpers.go, crypto/helpers_test.go, x/validators/controller_test.go, x/validators/errors.go, x/validators/model.go
This is my work in progress branch for https://github.com/iov-one/weave/issues/269
I am working on this for the 3rd day, so I thought I will present what I have so far before spending more time on this issue. 3 days is a lot of time and it's not finished yet.
All questions I will add as diff comments below.
=> Update validator set issue 269

cmd/bnsd/scenarios/main_test.go, cmd/bnsd/scenarios/wallet_test.go
Covers  `GconfCollectorAddress` and `FeeDecorator`.
=> Add test scenario with tx fee

README.md
=> Add compatibility charts

cmd/bcpd/README.md
Part of https://github.com/iov-one/weave/issues/278
=> Create bcpd application README file.

cmd/bnsd/client/client.go, cmd/bnsd/scenarios/main_test.go, cmd/bnsd/scenarios/wallet_test.go
Add acceptance test scenario for token query
=> Add AT scenario to cover token query

cmd/bcpd/app/msg.go, cmd/bcpd/app/tx.go, cmd/bnsd/app/tx.go, tx.go, tx_test.go
=> Use type switch to extract message

errors/errors.go, x/cash/decorator.go, x/coin.go, x/validators/controller.go, x/validators/controller_test.go, x/validators/errors.go, x/validators/handler_test.go, x/validators/model.go, x/validators/msg.go
work on https://github.com/iov-one/weave/issues/309
=> refactor errors for validator module

.travis.yml, Makefile
enable protobuf linter on CI
fix #318
=> enable protobuf linter on CI

cmd/bnsd/scenarios/README.md
=> Update bsnd/scenarios README file

cmd/bnsd/scenarios/distribution_test.go
=> distribution extension acceptance tests

README.md, x/currency/codec.pb.go, x/currency/codec.proto, x/currency/handler.go, x/currency/handler_test.go, x/currency/init.go, x/currency/init_test.go, x/currency/model.go, x/currency/model_test.go, x/currency/msg.go
Fixes https://github.com/iov-one/weave/issues/207
=> sigfigs removed

x/cash/controller.go, x/cash/dynamicfee.go, x/cash/staticfee.go
Please have a look at the changes I have made to the original pull request.
Each change is done in its own commit so that it can be easily reviewed and reverted if needed.
=> Changes... ¯\_(ツ)_/¯

README.md
=> Bump required go version to 1.10

x/namecoin/handler.go, x/namecoin/handler_test.go
=> Deny namecoin issuance when issuer is nil

docs/_static/css/custom.css
Closes #373 
Use some colors from the styleguide and remove effects
=> Fix up docs colors

docs/proto/index.html, scripts/cleaned_protos.sh
* Support protodocs generation with OSX
* Regenerate `docs/proto/index.html`
=> Support protodocs generation with OSX

Gopkg.lock, cmd/bcpd/commands/init_test.go, cmd/bnsd/commands/init_test.go, conditions.go, conditions_test.go, crypto/bech32/bech32.go, crypto/bech32/bech32_test.go
Allow to specify a JSON serialized condition using bech32 encoding.
resolve #362
=> bech32 support

cmd/bnsd/scenarios/distribution_test.go, cmd/bnsd/scenarios/main_test.go, cmd/lsaddr/lsaddr.go, x/distribution/handler.go, x/distribution/handler_test.go, x/distribution/model.go
When computing the revenue account address, validate created condition
first.
fix #425
=> Fix revenue account computation

cmd/bnsd/app/msg.go, cmd/bnsd/client/tx.go, cmd/bnsd/scenarios/distribution_test.go, cmd/bnsd/scenarios/escrow_test.go, cmd/bnsd/scenarios/main_test.go, cmd/bnsd/scenarios/nft_test.go, cmd/bnsd/scenarios/validator_test.go, cmd/bnsd/scenarios/wallet_test.go
* Anti spam fee for all transactions
* Some product fees
See #377 
Includes path update for #346
=> Add fees to scenarios

cmd/bnsd/app/app.go, cmd/bnsd/app/init.go
Add msgfee to BNS app
* Initializer
* Decorator
=> Enable product fee for bns

CODEOWNERS
Let's see if this works without reviewers
=> Remove CODEOWNERS that cause trouble with auto-PR assignment

README.md
resolve #440 
I am not sure about tendermint version so I have just repeated the current one. I do not think we have updated our tendermint requirement.
=> update compability chart

README.md
Adressing https://github.com/iov-one/weave/pull/442#discussion_r268787411
Preview https://github.com/iov-one/weave/blob/842aa853e8599e83c35bbc655116ea431ff4a6ad/README.md#compatibility-charts
=> fix compability chart in README

x/sigs/decorator.go, x/sigs/decorator_test.go
For each successfully verified signature in `x/sigs` decorator change a
fee.
resolve #429
=> Charge gas for signature verification.

cmd/bcpd/app/app_test.go, cmd/bnsd/app/app_nft_test.go, cmd/bnsd/app/app_test.go, cmd/bnsd/app/testdata/fixtures/app.go, cmd/bnsd/client/testdata/genesis.json, cmd/bnsd/client/testdata/genesis_json.md, cmd/bnsd/scenarios/main_test.go, cmd/bnsd/scenarios/nft_test.go
Resolves #377 
Test genesis and doc for the zebranet changes.
=> Genesis doc and test setup for bns testnet

app/helpers.go, app/store.go
I would like to keep this logic in app, without bringing any complex dependencies.
It was used and tested and I will make use of it again soon....
=> Save abci store

docs/mycoind/installation.rst, docs/mycoind/iovcore.rst
=> docs: remove outdated sections

cmd/bnsd/app/app.go, cmd/bnsd/app/init.go, x/msgfee/antispam_query.go, x/msgfee/antispam_query_test.go
Fixes https://github.com/iov-one/weave/issues/265 leftovers
=> Implemented anti-spam fee query

weavetest/assert/assert.go, x/sigs/controller_test.go, x/sigs/decorator_test.go, x/sigs/model_test.go
`assert.Panics` added as it is used in many places. 
part of #429
=> x/sigs: refactor tests

x/multisig/context_test.go, x/multisig/decorator_test.go
=> x/multisig: cleanup tests

x/auth_test.go, x/doc_test.go, x/persistent_test.go
=> weave/x: cleanup tests

coin/coin_test.go, x/cash/controller_test.go
coin and x/cash: tests cleanup  
part of issue #249
=> coin and x/cash: tests cleanup 

docs/deployment/configuration.rst, docs/mycoind/installation.rst
=> docs: update

docs/proto/index.html, x/gov/codec.pb.go, x/gov/codec.proto, x/gov/doc.go, x/gov/init.go, x/gov/init_test.go, x/gov/model.go
* Genesis initializer for Electorate and Election rules
* model validation rules proposal
See #439
=> Governance initializers

errors/stacktrace_test.go
=> errors: remove testify

crypto/doc.go, doc.go
formatting all packages: `go fmt $(go list ./... | grep -v "/vendor/")`
=> Go formatting only

CHANGELOG.md
Bootstrap CHANGELOG.md file that will be manually maintained.
More information at
https://github.com/iov-one/ops/wiki/How-do-we-work#changelog
resolve #466
=> CHANGELOG.md file created and initialized

store/iavl/adapter_test.go
Refactor `store/iavl` tests to not use testify and use map to declare
test cases.
part of #249
=> store/iavl: refactor tests

crypto/ed25519_test.go
remove testify from tests
part of #249
=> crypto: refactor tests

x/gov/bucket.go, x/gov/handler.go, x/gov/handler_test.go, x/gov/model.go, x/utils/doc.go
* Allow changing a vote
* Sanity check to prevent overflows in counting
* Verify votes stored in archive
Resolves #469
=> Allow changing vote

x/utils/logging.go
Refactor `logDuration` function to make the flow easier to understand.
This is part of the #525 issue refactoring.
=> x/utils: refactor handler logger

crypto/doc.go, doc.go, gconf/doc.go, migration/doc.go
Package level documentation comment must be written before the package
name declaration.
=> weave: update doc.go files

CHANGELOG.md, Makefile, docs/proto/index.html, x/currency/codec.pb.go, x/currency/codec.proto, x/currency/handler.go, x/currency/handler_test.go, x/currency/init_test.go, x/currency/model.go, x/currency/model_test.go, x/currency/msg.go, x/currency/msg_test.go, x/nft/base/handler.go, x/nft/base/handler_test.go, x/nft/codec.pb.go, x/nft/codec.proto, x/nft/model.go, x/nft/model_test.go, x/nft/msg.go, x/nft/msg_test.go
Part of https://github.com/iov-one/weave/issues/564
=> schema migration: x/nft, x/currency

README.md
I had created this channel before to bring some attraction for weave into the Tendermint community (also on riot.im). 
I think it would be good to get some feedback from other people using weave or interested in weave to improve the framework and develop it further.
=> Add link to (unofficial) community channel on riot.

orm/idgen_bucket.go, orm/idgen_bucket_test.go, x/distribution/model.go
Extract common id generating functionality into a new bucket type.
=> Add id generating orm bucket

.travis.yml, CHANGELOG.md, app/store_test.go, client/client.go, client/client_test.go, cmd/bnsd/client/client.go, cmd/bnsd/client/client_test.go, cmd/bnsd/client/testdata/genesis.json, cmd/bnsd/client/testdata/wallets.json, cmd/bnsd/scenarios/main_test.go, commands/server/start.go, go.mod, go.sum
Fixes https://github.com/iov-one/weave/issues/562
=> Feature/tm 0.31.5

docs/proto/index.html, errors/errors.go, orm/codec.pb.go, orm/codec.proto, orm/model.go, orm/versioning_bucket.go, orm/versioning_bucket_test.go
* New versioning bucket
Replaces #592
=> Orm versioning bucket

x/gov/bucket.go, x/gov/handler.go, x/gov/handler_test.go, x/gov/init.go
Replace classic bucket with idgen bucket in preparation for versioning.
* Removes obsolete code
=> Cleanup gov module with idgen bucket

client/client.go, client/main_test.go, client/test_helper.go, client/wrapper_test.go, cmd/bnsd/client/main_test.go, cmd/bnsd/scenarios/main_test.go
=> client: consolidate adaptive startup code into a test helper

client/client.go, client/client_test.go, client/types.go
Fixes #608 
@ethanfrey please review this to see if the approach makes sense.  I didn't want to introduce this to bnsd client, because I think that it should probably start using weave client first?
=> client: introduce options

cmd/bnsd/main.go, commands/server/getblock.go, commands/server/init.go, commands/server/retry.go, examples/mycoind/commands/init_test.go
Fixes https://github.com/iov-one/weave/issues/486
=> commands/server: various improvements

docs/configuration/application.rst, docs/configuration/tendermint.rst, docs/configuration/validators.rst, docs/design/overview.rst, docs/design/transactionhandling.rst, docs/index.rst
Here I add information on configuring the application and tendermint,
as well as an introduction to the structure of the application code (`examples/mycoind`)
Please view current state of docs here https://weave.readthedocs.io/en/overhaul-docs/ and add comments to this issue
=> Overhaul docs part 2

cmd/bcpd/app/app.go, cmd/bnsd/app/app.go
potentially fixes #595, although I'm not entirely sure it's the best approach, my concerns are listed in this comment:
https://github.com/iov-one/weave/issues/595#issuecomment-491801918
=> dynamicfee: checkpoint usage clarification in bnsd/bcpd

app/chain.go, x/msgfee/antispam_fee_decorator.go, x/msgfee/antispam_fee_decorator_test.go, x/msgfee/fee_decorator.go
#trivial Cleanup
Picks up where #643 got stuck.
=> Msgfee update, take 2

Makefile
The old if statement in the Makefile was woefully broken.
Fixed it
=> Do not download and build prototool every time

cmd/bnsd/scenarios/multisig_test.go, x/msgfee/fee_decorator.go
multisig payment acceptance test
fix #563
#trivial
=> Multisig acceptance test issue 563

cmd/bnsd/scenarios/bnsdtest/bnsdtest.go, cmd/bnsd/scenarios/multisig_test.go
New value = 0.05 * 10^9
See #635
#trivial
=> Set antispam fee

CHANGELOG.md, cmd/bnsd/app/app.go, cmd/bnsd/app/app_test.go, cmd/bnsd/app/codec.pb.go, cmd/bnsd/app/codec.proto, cmd/bnsd/app/msg.go, docs/proto/index.html
Enabling batch in bnsd, as it is most likely needed in the governance contracts for token distribution, among other things. Leaving it commented out was not helping anyone.
Builds on #652 please review and merge that first
=> Enable batch in bnsd

x/namecoin/handler_test.go
Cleanup handler tests in `x/namecoin` extension.
#trivial
=> x/namecoin: cleanup handler tests

examples/mycoind/app/app_test.go, examples/mycoind/app/init_test.go, examples/mycoind/commands/init_test.go, examples/mycoind/commands/start_test.go, examples/mycoind/main.go
Some low hanging fruit that bothered me while working on tutorial
#trivial
=> Remove testify imports from mycoind tests

README.md
Link to Design Document is invalid
=> Fixes link to design document in README.md

CHANGELOG.md, cmd/bnsd/app/app_test.go, cmd/bnsd/app/testdata/fixtures/app.go, cmd/bnsd/scenarios/bnsdtest/bnsdtest.go, conditions.go, conditions_test.go
Closes #698 
Did some clean up of the sample genesis files in the tests and it does look nicer.
=> Use seq: for addresses in genesis file json

Makefile, scripts/build_protodocs_docker.sh
=>  prototool: bump to version with caching

Makefile, scripts/build_protodocs_docker.sh
Managed to merge the previous PR without these changes, should be good now!
=> prototool: bump to v0.2.2

coin/coin.go, coin/coins.go, errors/errors.go, errors/multi_test.go, x/cash/model.go, x/cash/msg.go
=> errors: fix wrapped multierr behavior

.travis.yml, store.go
=> travis: remove danger failing the build

CHANGELOG.md, cmd/bnscli/clitests/cli_test.go, cmd/bnscli/clitests/send_tokens_with_default_fee.test, cmd/bnscli/clitests/send_tokens_with_default_fee.test.gold, cmd/bnscli/clitests/send_tokens_with_fee.test, cmd/bnscli/clitests/send_tokens_with_fee.test.gold, cmd/bnscli/cmd_cash.go, cmd/bnscli/cmd_cash_test.go, cmd/bnscli/cmd_msgfee.go, cmd/bnscli/main.go
A new `cmd/bnscli with-fee` command implemented as requested in #742
=> Bnscli fee

CHANGELOG.md, x/gov/bucket.go
Closes #749 
* Add index from Elector (voter address) to Electorate
* Add index from Electorate ID to Proposal
These indexes are added to help client queries.
=> Add gov indexes

CHANGELOG.md, x/aswap/handler.go, x/aswap/handler_test.go
Do not limit swap timeout to be only a certain value in the future.
resolve #718
=> x/aswap: allow timeout to be any value after 1970-01-01

cmd/bnsd/app/app_nft_test.go, cmd/bnsd/app/testdata/fixtures/app.go, cmd/bnsd/scenarios/bnsdtest/bnsdtest.go, cmd/bnsd/scenarios/nft_test.go, cmd/bnsd/x/nft/username/bucket.go, cmd/bnsd/x/nft/username/handler.go, cmd/bnsd/x/nft/username/model.go
Metadata was introduced to the model and messages some time ago. It was
never initialized though.
This is required in order to complete https://github.com/iov-one/weave/issues/714
#trivial
=> cmd/bnsd: initialize metadata in nft/username implementation

.golangci.yaml, .travis.yml, Makefile
Initial take, fails locally due to my docker-machine having 1 gig of ram
=> lint: docker and ci

cmd/bnscli/clitests/batch.test, cmd/bnscli/clitests/batch_proposal.test, cmd/bnscli/clitests/keyaddr.test, cmd/bnscli/clitests/sign_send_tokens.test, cmd/cleanproto/tests/test.sh
Replace Linux specific shell commands with OSX compatible ones
Fixes #782
=> Fixes bnscli tests for OSX

CHANGELOG.md, cmd/bnsd/app/init.go, cmd/bnsd/scenarios/bnsdtest/bnsdtest.go, cmd/bnsd/scenarios/bnsdtest/env.go, cmd/bnsd/scenarios/username_test.go, cmd/bnsd/x/username/init.go, cmd/bnsd/x/username/init_test.go
Implement genesis initialization for the `x/username` extension. Install
it in the `cmd/bnsd` application.
resolve #794
=> bnsd/x/username: implement genesis initialization

x/distribution/msg.go
=> Go fmt only

CHANGELOG.md, cmd/bnscli/clitests/gov_delete_proposal.test, cmd/bnscli/clitests/gov_delete_proposal.test.gold, cmd/bnscli/clitests/gov_tally.test, cmd/bnscli/clitests/gov_tally.test.gold, cmd/bnscli/clitests/gov_vote.test, cmd/bnscli/clitests/gov_vote.test.gold, cmd/bnscli/cmd_gov.go, cmd/bnscli/cmd_gov_test.go, cmd/bnscli/gov-dev.md, cmd/bnscli/main.go
Adds gov functionality to bnscli to
- delete a proposal
- vote
- tally
See #772
=> Add gov support to bnscli

commands/server/init.go
Not an important change but I see this several times a day.
#trivial
=> Fix server initialisation message

abci_test.go, conditions_test.go, context_test.go, time_test.go, util_test.go
=> weave: remove convey and testify from conditions tests

x/batch/decorator_test.go, x/batch/msg_test.go
This is a WIP
work on #249 
#trivial
=> x/batch: initial test rewrite

CHANGELOG.md, cmd/bnsd/x/username/model.go, cmd/bnsd/x/username/model_test.go
=> x/username: add owner index

x/gov/bucket_test.go
Add some unit tests to cover electorate queries
#trivial
=> Electorate query tests

CHANGELOG.md, cmd/bnsd/scenarios/gov_test.go, query.go, x/gov/bucket.go, x/gov/bucket_test.go, x/gov/handler.go
Ensure all query paths follow the same naming convention.
resolve #849
=> unify query paths

commands/server/start.go
=> commands/server/start: recover from panics to cleanup the socket

coin/coin.go, x/gov/model.go, x/gov/msg.go, x/gov/sample_test.go
=> cleanup imports

x/msgfee/antispam_fee_decorator_test.go, x/msgfee/fee_decorator_test.go
Two set of benchmarks for testing performance of `FeeDecorator` and
`AntispamFeeDecorator` of the `x/msgfee` extension.
resolve #284
!nochangelog
=> x/msgfee: add decorator benchmarks

.github/ISSUE_TEMPLATE/feature_request.md
=> Add acceptance criteria section to feature template

CHANGELOG.md, cmd/bnsd/x/username/init.go, handler.go, handler_test.go
=> x/username: fix memory leak on username import

CHANGELOG.md, cmd/bnsd/app/app_test.go, x/batch/decorator.go
=> x/batch: bump to 15 max messages

x/sigs/controller_test.go
A new benchmark that tests `sigs.VerifySignature` function. This
function is called for every signed transaction, for each signature that
this a transaction provides. In the current implementation this function
is called separately for every signature before handlers `Check` and
`Deliver` callbacks.
Running on my local machine, results are:
goos: linux
goarch: amd64
pkg: github.com/iov-one/weave/x/sigs
BenchmarkVerifySignatures/memory_store_small_payload-4                  10000   174463 ns/op
BenchmarkVerifySignatures/memory_store_big_payload-4                     5000   285872 ns/op
BenchmarkVerifySignatures/hard_drive_backed_store_with_small_payload-4  10000   173257 ns/op
BenchmarkVerifySignatures/hard_drive_backed_store_with_bit_payload-4    10000   237035 ns/op
There is no …
=> x/sigs: add benchmark for signature verification

.gitignore, .travis.yml, contrib/README.md, contrib/apt-cacher/Dockerfile, contrib/apt-cacher/README.md
* Fix travisCI build command
* Add apt-cacher-ng Dockerfile and doc
#trivial
=> Bnsd gitian build updates

CHANGELOG.md, scripts/clean_protos.sh, spec/gogo/codec.proto, spec/proto/codec.proto
Related to https://github.com/iov-one/weave-starter-kit/pull/37
=> Fix protoc error in weave based projects that use spec

CHANGELOG.md
- `x/batch`: increase maximum number of messages to 15
- `cmd/bnscli`: a new command `mnemonic` was added for generating a random
mnemonic as described in BIP-39.
- `weave.Options`: add an option to stream json for lower memory footprint
when parsing large json objects.
- `cmd/bnscli`: when a transaction is submitted, for certain messages parse
returned response data and print it in a human readable format.
- `clean_protos.sh` appends `option go_package = "github.com/iov-one/weave";`
to prevent protoc error in weave based frameworks
- `cmd/bnscli` support for more query endpoints
- `bnsd/x/username` was updated and now the username validation rules are
defined dynamically via gconf powered configuration.
Breaking changes
- `cmd/bnscli`: `keygen` command was updated and requires a mnemonic …
=> weave 0.21.0 release

.travis.yml
with multiline commit messages
=> Fix Travis to work

tmtest/tmtest.go
Fix a race condition in shutting down a test tendermint server. In
addition to avoiding a race condition, the cleanup function is always
blocking until the tendermint process is gone.
The race condition can be seen here https://travis-ci.com/iov-one/weave/jobs/228499962
!nochangelog
=> tmtest: fix race condition in killing tendermint server

cmd/bnsd/app/codec.pb.go, cmd/bnsd/app/codec.proto, cmd/bnsd/x/username/codec.pb.go, docs/proto/index.html, spec/gogo/cmd/bnsd/app/codec.proto, spec/gogo/cmd/bnsd/x/username/codec.proto, spec/proto/cmd/bnsd/app/codec.proto, spec/proto/cmd/bnsd/x/username/codec.proto
On request from @webmaster128. 
#trivial
=> cmd/bnsd: multisig comments

cmd/bnscli/cmd_username.go
Username command must not require target when registering a username as
it is no longer required.
!nochangelog
=> update bnscli username registration command

weavetest/cron.go, weavetest/cron_test.go
Solve problem in https://github.com/iov-one/blog-tutorial/pull/35#discussion_r331446971
!nochangelog
=> weavetest: fix cron implementation

cmd/bnsd/app/codec.pb.go, cmd/bnsd/app/codec.proto, docs/proto/index.html, spec/gogo/cmd/bnsd/app/codec.proto, spec/proto/cmd/bnsd/app/codec.proto
=> improve multisig comment on bnsd.tx

errors/errors.go
Implement `Unwrap` method that is utilized by the stdlib `errors`
package since Go 1.13.
Errors implemented in weave cannot fully utilize introduce in Go 1.13
error functions. `errors.Is` or `errors.As` cannot be used instead of
`Is` method declared by weave error, becase Go errors package does not
support error groups.
We can at least ditch `Cause` and use more appropriate `Unwrap` method
to be one step closer to full compatibility.
resolve #970
!nochangelog
=> errors: implement Unwrap method

cmd/bnsd/app/gov_handler.go
Msgfee registration in gov handler is required in order to process
msgfee messages submitted through a proposal.
!nochangelog
=> add x/msgfee router to gov

cmd/bnsd/app/datamigration.go
=> update msgfee configuration data migration

cmd/bnsd/app/datamigration.go, cmd/bnsd/x/account/init.go, cmd/bnsd/x/account/init_test.go
=> bnsd: add a no-op migration for local-iov-devnet network

.travis.yml, CHANGELOG.md, README.md, go.mod, go.sum
Upgrade minimal Go version.
Upgrade Tendermint.
=> minimal Go version is 1.12.14

CHANGELOG.md, cmd/bnsapi/bnsclient.go, cmd/bnsapi/bnsclient_test.go, cmd/bnsapi/handlers.go, cmd/bnsapi/handlers_test.go, cmd/bnsapi/main.go, cmd/bnsd/x/account/init.go, cmd/bnsd/x/account/model.go
A new handler added to `cmd/bnsapi` application.
Breaking change: `bnsd/x/account` indexes updated.
resolve #1110
=> cmd/bnsapi: add account.Account details query handler

cmd/bnsd/app/datamigration.go
Add `iov-dancenet` to all `bnsd` data migrations.
!nochangelog
=> update bnsd datamigration allowed chains

CHANGELOG.md, cmd/bnsd/app/gov_handler.go
Add datamigration routing to proposal handler.
=> bnsd: allow datamigration to be executed by a proposal

cmd/bnsd/app/datamigration.go
=> datamigration: change msgfee owner to economicExecutors

cmd/bnsd/x/account/README.md
=> account readme

cmd/bnscli/cmd_query.go, cmd/bnsd/app/app.go, cmd/bnsd/x/preregistration/handler.go
```sh
bnscli query -path "/preregistrationrecords" \
| jq -r '.[].Value | .domain + "\t" +  .owner'
```
resolve #1144
!nochangelog
=> allow to query preregistration records

cmd/bnsd/app/datamigration.go
=> merge all 1.0 release migrations together

CHANGELOG.md
=> version 1.0 release

CHANGELOG.md, cmd/bnscli/clitests/account_register_domain.test, cmd/bnscli/clitests/account_register_domain.test.gold, cmd/bnscli/cmd_account.go, cmd/bnscli/cmd_query.go
Changed boolean values to string as input. 
Related issue:
https://stackoverflow.com/a/27411724/12566604
=> cmd/bnscli: Fix boolean flag bug

cmd/bnsd/app/codec.pb.go, cmd/bnsd/app/datamigration.go, cmd/bnsd/x/termdeposit/codec.pb.go, crypto/ed25519_test.go, orm/helpers_test.go
=> Format the project

CHANGELOG.md, cmd/bnsd/app/app.go, cmd/bnsd/app/codec.pb.go, cmd/bnsd/app/datamigration.go, cmd/bnsd/x/termdeposit/codec.pb.go, crypto/ed25519_test.go, orm/helpers_test.go, x/msgfee/handler.go
Related to https://github.com/iov-one/bns/issues/11
=> bnsd: Expose msgfee bucket to the query router

.travis.yml
This PR aims to provide a curl download endpoint for the external integrators of weave and bnsd to integrate protoc in their process easily.
!nochangelog
=> Provide weave proto spec in the releases

cmd/bnsd/app/datamigration.go, cmd/bnsd/app/datamigration_test.go
Resolves https://github.com/iov-one/weave/issues/1173
Added support for the new chain IDs, and unit testing to check if the blockchain addresses are being correctly updated.
!NOCHANGELOG
=> Migrate new chain ids

.gitignore, x/gov/handler.go, x/gov/handler_test.go
Resolves https://github.com/iov-one/weave/issues/1176
This PR reverts this [commit](https://github.com/iov-one/weave/commit/d5a382419c786bcd826aeb18e7179bf54294ec9e).
!NOCHANGELOG
=> Revert PR1132

CHANGELOG.md, cmd/bnsd/x/account/handler.go, cmd/bnsd/x/account/handler_test.go
Resolves https://github.com/iov-one/weave/issues/1171
=> Change accounts owner when a new domain is transferred

.travis.yml, cmd/bnsd/x/account/handler.go
Resolves https://github.com/iov-one/weave/issues/1189
Fixed also travis ci file.
!NOCHANGELOG
=> Flush domain by loading account in batches

CHANGELOG.md, cmd/bnsd/x/account/handler.go, cmd/bnsd/x/account/handler_test.go
Resolves https://github.com/iov-one/weave/issues/1190
=> Clear account targets on transfer

CHANGELOG.md, cmd/bnsd/x/account/handler.go
Resolves https://github.com/iov-one/weave/issues/1188
Some error messages were updated to better reflect the spec.
=> fixed error messages to give more context

CHANGELOG.md, cmd/bnsd/x/account/handler.go, cmd/bnsd/x/account/handler_test.go
Resolves https://github.com/iov-one/weave/issues/1204
=> bnsd: fix domain renews empty account

cmd/dumpstate/cash.gold.json, cmd/dumpstate/dumpstate.go
Depends on https://github.com/iov-one/weave/pull/1218
Resolves https://github.com/iov-one/weave/issues/1216
!nochangelog
=> dumpstate: dont dump empty acc
